# Generated by Django 5.2.6 on 2026-05-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripthion',
            new_name='description',
        ),
    ]
